#!/usr/bin/env python3
"""Regenerate firmware/src/web_assets.h from firmware/web/index.html.

Embeds the gzip of the single-page UI as a C array, served with
Content-Encoding: gzip.  This avoids PlatformIO's flaky EMBED_FILES/.S
generation (its SCons layer does not replicate the IDF embed custom-command
for idf_component_register EMBED_FILES, so the .S is never produced).

Re-run after editing web/index.html:
    python firmware/scripts/gen_web_assets.py
Atomic write + gzip roundtrip validation (NFS-safe, mtime=0 deterministic).
"""
import gzip
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # firmware/
SRC  = os.path.join(ROOT, "web", "index.html")
OUT  = os.path.join(ROOT, "src", "web_assets.h")


def main():
    html = open(SRC, "r", encoding="utf-8").read()
    # Splice the busware logo (base64 PNG) into the data: URL placeholder so
    # the 26 KB blob isn't hand-edited in the HTML source.
    logo = open(os.path.join(ROOT, "web", "busware_logo.b64")).read().strip()
    assert "__LOGO__" in html, "index.html is missing the __LOGO__ placeholder"
    html = html.replace("__LOGO__", logo)
    data = html.encode("utf-8")
    gz   = gzip.compress(data, 9, mtime=0)
    assert gzip.decompress(gz) == data, "gzip roundtrip failed"

    rows = []
    for i in range(0, len(gz), 16):
        rows.append("  " + "".join("0x%02x," % b for b in gz[i:i + 16]))

    body = (
        "// AUTO-GENERATED by scripts/gen_web_assets.py — do not edit by hand.\n"
        "// gzip of web/index.html, served with Content-Encoding: gzip.\n"
        "// Re-run the script after editing the UI.\n"
        "#ifndef CDC2NET_WEB_ASSETS_H\n"
        "#define CDC2NET_WEB_ASSETS_H\n"
        "#include <stddef.h>\n"
        "static const unsigned char index_html_gz[] = {\n"
        + "\n".join(rows) + "\n"
        "};\n"
        "static const size_t index_html_gz_len = %d;\n"
        "#endif // CDC2NET_WEB_ASSETS_H\n"
    ) % len(gz)

    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        f.write(body)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, OUT)
    print("web_assets.h: %d html -> %d gz bytes" % (len(data), len(gz)))


main()
