#!/usr/bin/env python3
"""Regenerate firmware/main/web_assets.h from firmware/web/index.html.

Embeds the gzip of the single-page UI as a C array, served with
Content-Encoding: gzip.  This avoids PlatformIO's flaky EMBED_FILES/.S
generation (its SCons layer does not replicate the IDF embed custom-command
for idf_component_register EMBED_FILES, so the .S is never produced).

Re-run after editing web/index.html:
    python firmware/scripts/gen_web_assets.py
Atomic write + gzip roundtrip validation (NFS-safe, mtime=0 deterministic).
"""
import gzip
import os
import re
import subprocess
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # firmware/
SRC  = os.path.join(ROOT, "web", "index.html")
OUT  = os.path.join(ROOT, "main", "web_assets.h")


def _read_text_source_nfs(path, markers=(b"<html", b"</html>"), retries=6):
    """NFS-safe Read einer Text-Quelle. Ein Read ueber NFS kann einen
    NUL-praefixierten ersten 4-KB-Block liefern (lazy write-back race): die
    Laenge stimmt, der Inhalt ist Muell. Validiere den INHALT (keine NUL-Bytes
    + erwartete Marker, nicht nur Laenge) und lies bei Korruption neu — mit
    posix_fadvise(DONTNEED)-Cache-Drop, damit der Retry frisch vom NFS-Server
    holt; sonst lauter Abbruch. Der gzip-roundtrip-Assert unten faengt das
    NICHT, weil er gegen die schon-korrupte Quelle prueft. Portiert aus
    BoseFix32 scripts/version_bump.py (Vorfall 2026-06-03: web/index.html mit
    4096 NUL-Bytes am Anfang -> embeddete UI ohne <head>/<title>)."""
    last = b""
    for attempt in range(retries):
        with open(path, "rb") as fi:
            raw = fi.read()
        if raw and b"\x00" not in raw and all(m in raw.lower() for m in markers):
            return raw
        last = raw
        print("[nfs-read] %s sieht korrupt aus (Versuch %d/%d: len=%d, NUL=%d) "
              "-> Page-Cache verwerfen + re-read"
              % (os.path.basename(path), attempt + 1, retries, len(raw),
                 raw.count(bytes(1))))
        try:
            fd = os.open(path, os.O_RDONLY)
            try:
                os.posix_fadvise(fd, 0, 0, os.POSIX_FADV_DONTNEED)
            finally:
                os.close(fd)
        except (AttributeError, OSError):
            pass
        time.sleep(0.4)
    raise RuntimeError(
        "[nfs-read] %s blieb nach %d Reads korrupt (NUL=%d Bytes, len=%d) — "
        "NFS-write-back-race oder Quelle persistent kaputt. Abbruch, statt eine "
        "kaputte UI zu embedden. Quelle pruefen / aus git wiederherstellen."
        % (path, retries, last.count(bytes(1)), len(last)))


def _check_js_syntax(html):
    """Pflicht-Gate: alle <script>-Bloecke durch `node --check` jagen, BEVOR
    irgendetwas embedded wird. Ein Syntaxfehler im Page-JS killt beim Laden das
    GESAMTE Script — die Kacheln bleiben dann leer, und das faellt erst im
    Browser auf (Vorfall 2026-07-30: doppeltes `const h` im selben Scope,
    dynamischer Header-Titel vs. j.health — eine Firmware lang unbemerkt
    ausgeliefert). node fehlt = Abbruch, nicht Warnung: ein Gate, das still
    uebersprungen wird, ist keins."""
    js = "\n".join(re.findall(r"<script>(.*?)</script>", html, re.S))
    if not js.strip():
        raise RuntimeError("[js-gate] kein <script>-Block in index.html gefunden — "
                           "Quelle kaputt?")
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(js)
        tmp = f.name
    try:
        r = subprocess.run(["node", "--check", tmp],
                           capture_output=True, text=True)
    except FileNotFoundError:
        os.unlink(tmp)
        raise RuntimeError("[js-gate] `node` nicht gefunden — das Syntax-Gate ist "
                           "Pflicht. node installieren oder auf einem Host mit "
                           "node generieren.")
    os.unlink(tmp)
    if r.returncode != 0:
        raise RuntimeError("[js-gate] SyntaxError im Page-JS — web_assets.h NICHT "
                           "regeneriert:\n" + r.stderr.strip())
    print("[js-gate] node --check: Page-JS syntaktisch OK")


def main():
    html = _read_text_source_nfs(SRC).decode("utf-8")
    _check_js_syntax(html)
    # Splice the busware logo (base64 PNG) into the data: URL placeholder so
    # the 26 KB blob isn't hand-edited in the HTML source.
    logo = _read_text_source_nfs(
        os.path.join(ROOT, "web", "busware_logo.b64"), markers=()
    ).decode("utf-8").strip()
    assert "__LOGO__" in html, "index.html is missing the __LOGO__ placeholder"
    html = html.replace("__LOGO__", logo)
    data = html.encode("utf-8")
    gz   = gzip.compress(data, 9, mtime=0)
    assert gzip.decompress(gz) == data, "gzip roundtrip failed"

    rows = []
    for i in range(0, len(gz), 16):
        rows.append("  " + "".join("0x%02x," % b for b in gz[i:i + 16]))

    body = (
        "// AUTO-GENERATED by scripts/gen_web_assets.py — do not edit by hand.\n"
        "// gzip of web/index.html, served with Content-Encoding: gzip.\n"
        "// Re-run the script after editing the UI.\n"
        "#ifndef CDC2NET_WEB_ASSETS_H\n"
        "#define CDC2NET_WEB_ASSETS_H\n"
        "#include <stddef.h>\n"
        "static const unsigned char index_html_gz[] = {\n"
        + "\n".join(rows) + "\n"
        "};\n"
        "static const size_t index_html_gz_len = %d;\n"
        "#endif // CDC2NET_WEB_ASSETS_H\n"
    ) % len(gz)

    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        f.write(body)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, OUT)
    print("web_assets.h: %d html -> %d gz bytes" % (len(data), len(gz)))


main()
