// SPDX-License-Identifier: GPL-2.0-or-later
// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef VERSION_H
#define VERSION_H

#define FW_VERSION_MAJOR  0
#define FW_VERSION_MINOR  1
#define FW_VERSION_BUILD  48

#define FW_VERSION_STRING "0.1.48"
#define FW_BUILD_DATE     "2026-06-02 16:43:52"

#endif // VERSION_H
