// SPDX-License-Identifier: GPL-2.0-or-later
//
// webui.c — HTTP status/OTA server for CDC2NET (M4 part 1).
// Stripped from RFNETHM webui.c: status + log + reboot + OTA + update-check +
// captive redirects.  No auth / wifi-config / diagnostics yet (M4 part 2).

#include "webui.h"
#include "version.h"
#include "bridge.h"
#include "net.h"
#include "source_usb.h"
#include "sink_tcp.h"
#include "log_buffer.h"
#include "ota_check.h"
#include "config.h"
#include "health.h"
#include <stdlib.h>

#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_app_desc.h"
#include "esp_ota_ops.h"
#include "esp_partition.h"
#include "esp_heap_caps.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>

static const char *TAG = "webui";
static httpd_handle_t s_http;

// Embedded single-page dashboard (generated by scripts/gen_web_assets.py;
// gzip C array — avoids PlatformIO's flaky EMBED_FILES .S generation).
#include "web_assets.h"

static const char *reset_reason_str(esp_reset_reason_t r)
{
    switch (r) {
    case ESP_RST_POWERON:  return "POWERON";
    case ESP_RST_EXT:      return "EXT";
    case ESP_RST_SW:       return "SW";
    case ESP_RST_PANIC:    return "PANIC";
    case ESP_RST_INT_WDT:  return "INT_WDT";
    case ESP_RST_TASK_WDT: return "TASK_WDT";
    case ESP_RST_WDT:      return "WDT";
    case ESP_RST_BROWNOUT: return "BROWNOUT";
    default:               return "UNKNOWN";
    }
}

// Escape a string for embedding in a JSON string literal.
static void json_escape(const char *src, char *dst, size_t dst_cap)
{
    if (dst_cap == 0) return;
    if (!src) src = "";
    size_t i = 0;
    while (*src && i + 7 < dst_cap) {
        unsigned char c = (unsigned char)*src++;
        if (c == '"' || c == '\\') {
            dst[i++] = '\\';
            dst[i++] = c;
        } else if (c < 0x20) {
            int w = snprintf(dst + i, dst_cap - i, "\\u%04x", c);
            if (w < 0) break;
            i += (size_t)w;
        } else {
            dst[i++] = c;
        }
    }
    dst[i] = '\0';
}

static esp_err_t h_index(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    httpd_resp_set_hdr(req, "Cache-Control", "max-age=300");
    return httpd_resp_send(req, (const char *)index_html_gz, index_html_gz_len);
}

// ───── /api/status ──────────────────────────────────────────────────────

// Minimal JSON string-field extract (no nested escapes). Returns 0 on success.
static int json_field(const char *in, const char *key, char *out, size_t out_cap)
{
    char needle[40];
    snprintf(needle, sizeof(needle), "\"%s\"", key);
    const char *p = strstr(in, needle);
    if (!p) return -1;
    p = strchr(p + strlen(needle), ':');
    if (!p) return -1;
    p++;
    while (*p == ' ' || *p == '\t') p++;
    size_t n = 0;
    if (*p == '"') {                       // quoted string value
        p++;
        while (*p && *p != '"' && n + 1 < out_cap) {
            if (*p == '\\' && p[1]) p++;
            out[n++] = *p++;
        }
        out[n] = '\0';
        return (*p == '"') ? 0 : -1;
    }
    // unquoted value (number / true / false / null) — read to delimiter.
    while (*p && *p != ',' && *p != '}' && *p != ']' &&
           *p != ' ' && *p != '\t' && *p != '\n' && *p != '\r' && n + 1 < out_cap) {
        out[n++] = *p++;
    }
    out[n] = '\0';
    return n ? 0 : -1;
}

// JSON boolean / "true" / 1 lookup.  false if missing or non-truthy.
static bool json_field_truthy(const char *in, const char *key)
{
    char needle[40];
    snprintf(needle, sizeof(needle), "\"%s\"", key);
    const char *p = strstr(in, needle);
    if (!p) return false;
    p = strchr(p + strlen(needle), ':');
    if (!p) return false;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '"') p++;
    return strncmp(p, "true", 4) == 0 || *p == '1';
}

static int read_body(httpd_req_t *req, char *buf, size_t cap)
{
    int total = 0;
    while (total < (int)cap - 1) {
        int r = httpd_req_recv(req, buf + total, (size_t)((int)cap - 1 - total));
        if (r <= 0) {
            if (r == HTTPD_SOCK_ERR_TIMEOUT) continue;
            break;
        }
        total += r;
    }
    buf[total] = '\0';
    return total;
}

static const char *authmode_str(uint8_t a)
{
    switch (a) {
    case 0: return "open";    case 1: return "wep";       case 2: return "wpa";
    case 3: return "wpa2";    case 4: return "wpa-wpa2";  case 5: return "wpa2-ent";
    case 6: return "wpa3";    case 7: return "wpa2-wpa3"; default: return "?";
    }
}

// ───── /api/status ──────────────────────────────────────────────────────

static esp_err_t h_status(httpd_req_t *req)
{
    bridge_stats_t     bs;  bridge_get_stats(&bs);
    source_usb_stats_t us;  source_usb_get_stats(&us);
    sink_tcp_stats_t   ts;  sink_tcp_get_stats(&ts);

    char ssid_esc[200];
    json_escape(net_ssid(), ssid_esc, sizeof(ssid_esc));
    char manuf_esc[100], prod_esc[100];
    json_escape(us.manuf,   manuf_esc, sizeof(manuf_esc));
    json_escape(us.product, prod_esc, sizeof(prod_esc));

    cdc2net_cfg_t cfg;
    config_load(&cfg);

    char buf[1850];
    int n = snprintf(buf, sizeof(buf),
        "{"
          "\"fw\":{\"version\":\"%s\",\"built\":\"%s\"},"
          "\"net\":{\"up\":%s,\"ssid\":\"%s\",\"ip\":\"%s\",\"gw\":\"%s\","
                  "\"ap\":%s,\"host\":\"%s\"},"
          "\"usb\":{\"connected\":%s,\"vid\":\"%04X\",\"pid\":\"%04X\","
                  "\"manuf\":\"%s\",\"product\":\"%s\",\"rx\":%u,\"tx\":%u},"
          "\"br\":{\"sinks\":%u,\"rx_bytes\":%u,\"tx_bytes\":%u,\"rx_pumps\":%u,\"tx_drop\":%u},"
          "\"tcp\":{\"port\":%u,\"clients\":%d,\"accepts\":%u,\"rx\":%u,\"tx\":%u},"
          "\"cfg\":{\"tcp_port\":%u,\"static_ip\":%s,\"ip\":\"%s\",\"mask\":\"%s\","
                  "\"gw\":\"%s\",\"dns\":\"%s\",\"wdt_enable\":%s,\"wdt_timeout_s\":%u},"
          "\"sys\":{\"uptime_s\":%u,\"free_heap\":%u,\"min_free_heap\":%u,"
                   "\"largest_block\":%u,\"reset_reason\":\"%s\"},"
          "\"health\":{\"boot_count\":%u,\"crash_count\":%u,\"wdt_reboots\":%u,"
                      "\"wdt_subscribed\":%s}"
        "}",
        FW_VERSION_STRING, FW_BUILD_DATE,
        net_is_connected() ? "true" : "false", ssid_esc, net_ip_str(), net_gw_str(),
        net_is_ap_mode() ? "true" : "false", net_hostname(),
        us.connected ? "true" : "false", us.vid, us.pid,
        manuf_esc, prod_esc,
        (unsigned)us.rx_bytes, (unsigned)us.tx_bytes,
        (unsigned)bs.sink_count, (unsigned)bs.rx_bytes_total,
        (unsigned)bs.tx_bytes_total, (unsigned)bs.rx_pumps_total,
        (unsigned)bs.tx_dropped_not_ready,
        ts.port, ts.active_clients, (unsigned)ts.total_accepts,
        (unsigned)ts.rx_bytes_from_clients, (unsigned)ts.tx_bytes_to_clients,
        cfg.tcp_port, cfg.static_ip ? "true" : "false", cfg.ip, cfg.mask,
        cfg.gw, cfg.dns, cfg.wdt_enable ? "true" : "false", (unsigned)cfg.wdt_timeout_s,
        (unsigned)(esp_log_timestamp() / 1000),
        (unsigned)esp_get_free_heap_size(),
        (unsigned)esp_get_minimum_free_heap_size(),
        (unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT),
        reset_reason_str(esp_reset_reason()),
        (unsigned)health_boot_count(), (unsigned)health_crash_count(),
        (unsigned)health_wdt_reboots(),
        health_wdt_subscribed() ? "true" : "false");

    if (n < 0 || n >= (int)sizeof(buf)) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "buf overflow");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, buf, n);
}

static esp_err_t h_log(httpd_req_t *req)
{
    uint32_t since = 0;
    char qs[64];
    if (httpd_req_get_url_query_str(req, qs, sizeof(qs)) == ESP_OK) {
        char val[16];
        if (httpd_query_key_value(qs, "since", val, sizeof(val)) == ESP_OK) {
            since = (uint32_t)strtoul(val, NULL, 10);
        }
    }
    static char body[8192];
    static char lines[7000];
    uint32_t head = 0, oldest = 0;
    size_t cnt = log_buffer_get_since(since, lines, sizeof(lines), &head, &oldest);
    int p = snprintf(body, sizeof(body),
                     "{\"head\":%u,\"oldest\":%u,\"count\":%u,\"lines\":[%s]}",
                     (unsigned)head, (unsigned)oldest, (unsigned)cnt, lines);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, body, p);
}

static void delayed_reboot_task(void *arg)
{
    (void)arg;
    vTaskDelay(pdMS_TO_TICKS(500));
    esp_restart();
}

static esp_err_t h_reboot(httpd_req_t *req)
{
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"rebooting\":true}", 18);
    xTaskCreate(delayed_reboot_task, "reboot", 2048, NULL, 5, NULL);
    return ESP_OK;
}

// ───── OTA — raw firmware.bin body, streamed into the passive OTA slot ──

static esp_err_t h_ota(httpd_req_t *req)
{
    const esp_partition_t *upd = esp_ota_get_next_update_partition(NULL);
    if (!upd) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "no OTA partition");
        return ESP_FAIL;
    }

    const int min_len = 256 * 1024;
    const int max_len = (int)upd->size - 0x1000;
    if (req->content_len < min_len || req->content_len > max_len) {
        ESP_LOGW(TAG, "OTA rejected: content_len=%d out of range [%d, %d]",
                 req->content_len, min_len, max_len);
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "content_len out of range");
        return ESP_FAIL;
    }
    ESP_LOGW(TAG, "OTA: writing to '%s' (size %u, content_len %d)",
             upd->label, (unsigned)upd->size, req->content_len);

    esp_ota_handle_t h = 0;
    if (esp_ota_begin(upd, OTA_SIZE_UNKNOWN, &h) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "ota_begin");
        return ESP_FAIL;
    }

    // First 288 B = image_header(24) + segment_header(8) + esp_app_desc(256).
    // Validate magic + project_name so a wrong image can't be flashed.
    uint8_t hdr_buf[288];
    size_t  hdr_filled    = 0;
    bool    hdr_validated = false;
    char    new_version[33] = {0};

    char buf[1024];
    int  remaining = req->content_len;
    int  written   = 0;
    while (remaining > 0) {
        int chunk = remaining > (int)sizeof(buf) ? (int)sizeof(buf) : remaining;
        int r = httpd_req_recv(req, buf, chunk);
        if (r <= 0) {
            if (r == HTTPD_SOCK_ERR_TIMEOUT) continue;
            esp_ota_abort(h);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "recv error");
            return ESP_FAIL;
        }
        if (!hdr_validated) {
            size_t take = sizeof(hdr_buf) - hdr_filled;
            if (take > (size_t)r) take = (size_t)r;
            memcpy(hdr_buf + hdr_filled, buf, take);
            hdr_filled += take;
            if (hdr_filled == sizeof(hdr_buf)) {
                const esp_app_desc_t *nd = (const esp_app_desc_t *)&hdr_buf[32];
                if (nd->magic_word != ESP_APP_DESC_MAGIC_WORD) {
                    esp_ota_abort(h);
                    httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST,
                                        "not an ESP image (magic mismatch)");
                    return ESP_FAIL;
                }
                snprintf(new_version, sizeof(new_version), "%.*s",
                         (int)sizeof(nd->version), nd->version);
                const esp_app_desc_t *cd = esp_app_get_description();
                if (strncmp(nd->project_name, cd->project_name,
                            sizeof(nd->project_name)) != 0) {
                    esp_ota_abort(h);
                    ESP_LOGE(TAG, "OTA: project_name mismatch: image='%.32s' running='%.32s'",
                             nd->project_name, cd->project_name);
                    httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "project_name mismatch");
                    return ESP_FAIL;
                }
                ESP_LOGW(TAG, "OTA: image v%s (running v%.32s)", new_version, cd->version);
                hdr_validated = true;
            }
        }
        if (esp_ota_write(h, buf, r) != ESP_OK) {
            esp_ota_abort(h);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "ota_write");
            return ESP_FAIL;
        }
        remaining -= r;
        written   += r;
    }
    if (!hdr_validated) {
        esp_ota_abort(h);
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "image too small");
        return ESP_FAIL;
    }
    if (esp_ota_end(h) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "ota_end");
        return ESP_FAIL;
    }
    if (esp_ota_set_boot_partition(upd) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "set_boot");
        return ESP_FAIL;
    }
    ESP_LOGW(TAG, "OTA done — %d bytes — rebooting to v%s in 500 ms", written, new_version);

    const esp_app_desc_t *cd = esp_app_get_description();
    char j[200];
    int jn = snprintf(j, sizeof(j),
                      "{\"ota\":\"ok\",\"bytes\":%d,\"from\":\"%.32s\",\"to\":\"%s\"}",
                      written, cd->version, new_version);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, j, jn);
    xTaskCreate(delayed_reboot_task, "reboot-ota", 2048, NULL, 5, NULL);
    return ESP_OK;
}

// ───── /api/update/check — online manifest version check ────────────────

static esp_err_t h_update_check(httpd_req_t *req)
{
    bool refresh = (req->method == HTTP_POST);
    if (!refresh) {
        char qbuf[32];
        if (httpd_req_get_url_query_str(req, qbuf, sizeof(qbuf)) == ESP_OK) {
            char v[8];
            if (httpd_query_key_value(qbuf, "refresh", v, sizeof(v)) == ESP_OK
                && v[0] && v[0] != '0') {
                refresh = true;
            }
        }
    }
    if (refresh) ota_check_refresh();   // synchronous, may block ~1-3 s

    char body[320];
    int n = ota_check_status_json(body, sizeof(body));
    if (n < 0) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "status buffer too small");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, body, n);
}

// ───── Captive-portal probe redirects ───────────────────────────────────

static esp_err_t h_captive_redirect(httpd_req_t *req)
{
    char loc[64];
    snprintf(loc, sizeof(loc), "http://%s/", net_ip_str());
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", loc);
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, NULL, 0);
}

static esp_err_t h_not_found(httpd_req_t *req, httpd_err_code_t err)
{
    (void)err;
    if (net_is_ap_mode()) return h_captive_redirect(req);
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Not Found");
    return ESP_FAIL;
}

// ───── init ─────────────────────────────────────────────────────────────

// ───── /api/config ──────────────────────────────────────────────────────

static esp_err_t h_config_get(httpd_req_t *req)
{
    cdc2net_cfg_t c;
    config_load(&c);
    char buf[320];
    int n = snprintf(buf, sizeof(buf),
        "{\"tcp_port\":%u,\"static_ip\":%s,\"ip\":\"%s\",\"mask\":\"%s\","
        "\"gw\":\"%s\",\"dns\":\"%s\",\"wdt_enable\":%s,\"wdt_timeout_s\":%u}",
        c.tcp_port, c.static_ip ? "true" : "false", c.ip, c.mask, c.gw, c.dns,
        c.wdt_enable ? "true" : "false", (unsigned)c.wdt_timeout_s);
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, buf, n);
}

// POST JSON: {tcp_port,static_ip,ip,mask,gw,dns,wdt_enable,wdt_timeout_s}.
// Overlays the current config; saved to NVS, applied on reboot.
static esp_err_t h_config_post(httpd_req_t *req)
{
    char body[400];
    read_body(req, body, sizeof(body));

    cdc2net_cfg_t c;
    config_load(&c);

    char v[24];
    if (json_field(body, "tcp_port", v, sizeof(v)) == 0) {
        int p = atoi(v);
        if (p > 0 && p < 65536) c.tcp_port = (uint16_t)p;
    }
    c.static_ip = json_field_truthy(body, "static_ip");
    json_field(body, "ip",   c.ip,   sizeof(c.ip));
    json_field(body, "mask", c.mask, sizeof(c.mask));
    json_field(body, "gw",   c.gw,   sizeof(c.gw));
    json_field(body, "dns",  c.dns,  sizeof(c.dns));
    c.wdt_enable = json_field_truthy(body, "wdt_enable");
    if (json_field(body, "wdt_timeout_s", v, sizeof(v)) == 0) {
        int t = atoi(v);
        if (t >= 30) c.wdt_timeout_s = (uint32_t)t;
    }

    if (c.static_ip && (c.ip[0] == '\0' || c.mask[0] == '\0' || c.gw[0] == '\0')) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "static IP needs ip/mask/gw");
        return ESP_FAIL;
    }
    if (config_save(&c) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "save failed");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, "{\"saved\":true,\"reboot_required\":true}",
                           HTTPD_RESP_USE_STRLEN);
}

// ───── /api/serial — per-device line coding (baud/bits/parity/stop) ──────

static const char *lcsrc_str(uint8_t s) {
    return s == 1 ? "nvs" : (s == 2 ? "rfc2217" : "default");
}

static esp_err_t h_serial_get(httpd_req_t *req)
{
    source_usb_serial_info_t si;
    source_usb_get_serial_info(&si);
    serialcfg_item_t items[SERIALCFG_MAX];
    int nitems = serialcfg_list(items, SERIALCFG_MAX);

    char key_esc[80], ser_esc[80];
    json_escape(si.key,    key_esc, sizeof(key_esc));
    json_escape(si.serial, ser_esc, sizeof(ser_esc));

    char buf[1024];
    int n = snprintf(buf, sizeof(buf),
        "{\"attached\":{\"connected\":%s,\"is_vcp\":%s,\"vid\":\"%04X\",\"pid\":\"%04X\","
          "\"serial\":\"%s\",\"key\":\"%s\"},"
        "\"effective\":{\"baud\":%u,\"bits\":%u,\"parity\":%u,\"stop\":%u,\"source\":\"%s\"},"
        "\"stored\":[",
        si.connected ? "true" : "false", si.is_vcp ? "true" : "false", si.vid, si.pid,
        ser_esc, key_esc,
        (unsigned)si.baud, si.bits, si.parity, si.stop, lcsrc_str(si.lc_source));
    for (int i = 0; i < nitems && n > 0 && n < (int)sizeof(buf) - 96; i++) {
        char k_esc[80];
        json_escape(items[i].key, k_esc, sizeof(k_esc));
        n += snprintf(buf + n, sizeof(buf) - n,
            "%s{\"key\":\"%s\",\"baud\":%u,\"bits\":%u,\"parity\":%u,\"stop\":%u}",
            i ? "," : "", k_esc, (unsigned)items[i].lc.baud,
            items[i].lc.bits, items[i].lc.parity, items[i].lc.stop);
    }
    if (n > 0 && n < (int)sizeof(buf) - 3)
        n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (n <= 0 || n >= (int)sizeof(buf)) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "buf overflow");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, buf, n);
}

// POST {key,baud,bits,parity,stop}  — store the per-device default (applied
// live if that device is attached and no RFC2217 client owns the port).
// POST {key,delete:true}            — forget the entry.
static esp_err_t h_serial_post(httpd_req_t *req)
{
    char body[256];
    read_body(req, body, sizeof(body));

    char key[SERIALCFG_KEY_LEN];
    if (json_field(body, "key", key, sizeof(key)) != 0 || key[0] == '\0') {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "key required");
        return ESP_FAIL;
    }
    if (json_field_truthy(body, "delete")) {
        serialcfg_delete(key);
        // If we just deleted the entry for the *attached* device (and no RFC2217
        // client owns the port), re-apply the global default live — otherwise
        // the effective line coding lingers at the now-orphaned NVS value still
        // labelled "nvs" instead of falling back to "default".  Mirrors the
        // upsert apply-live guard below; runs in the httpd task (no sink mutex
        // held), so apply_line_coding's tx_mtx never nests.
        bool reverted = false;
        source_usb_serial_info_t si;
        source_usb_get_serial_info(&si);
        if (si.connected && si.lc_source != 2 && strcmp(si.key, key) == 0) {
            serialcfg_lc_t d = serialcfg_default();
            reverted = (source_usb_apply_line_coding(d.baud, d.bits, d.parity,
                                                     d.stop, 0) == ESP_OK);
        }
        char resp[48];
        int n = snprintf(resp, sizeof(resp), "{\"deleted\":true,\"reverted\":%s}",
                         reverted ? "true" : "false");
        httpd_resp_set_type(req, "application/json");
        return httpd_resp_send(req, resp, n);
    }

    char v[16];
    serialcfg_lc_t lc = serialcfg_default();
    if (json_field(body, "baud", v, sizeof(v)) == 0) {
        long b = atol(v); if (b >= 300 && b <= 4000000) lc.baud = (uint32_t)b;
    }
    if (json_field(body, "bits", v, sizeof(v)) == 0) {
        int b = atoi(v); if (b >= 5 && b <= 8) lc.bits = (uint8_t)b;
    }
    if (json_field(body, "parity", v, sizeof(v)) == 0) {
        int p = atoi(v); if (p >= 0 && p <= 4) lc.parity = (uint8_t)p;
    }
    if (json_field(body, "stop", v, sizeof(v)) == 0) {
        int s = atoi(v); if (s >= 0 && s <= 2) lc.stop = (uint8_t)s;
    }

    if (serialcfg_upsert(key, &lc) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "save failed");
        return ESP_FAIL;
    }

    // Apply now if this is the attached device and no RFC2217 client controls it.
    bool applied = false;
    source_usb_serial_info_t si;
    source_usb_get_serial_info(&si);
    if (si.connected && si.lc_source != 2 && strcmp(si.key, key) == 0)
        applied = (source_usb_apply_line_coding(lc.baud, lc.bits, lc.parity,
                                                lc.stop, 1) == ESP_OK);

    char resp[64];
    int n = snprintf(resp, sizeof(resp), "{\"saved\":true,\"applied\":%s}",
                     applied ? "true" : "false");
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, resp, n);
}

// ───── /api/wifi — set creds / scan / forget ────────────────────────────

static esp_err_t h_wifi(httpd_req_t *req)
{
    char body[256];
    read_body(req, body, sizeof(body));
    char ssid[33] = {0}, pass[65] = {0};
    if (json_field(body, "ssid", ssid, sizeof(ssid)) != 0 || ssid[0] == '\0') {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "missing ssid");
        return ESP_FAIL;
    }
    json_field(body, "pass", pass, sizeof(pass));   // empty = open net
    if (net_persist_creds(ssid, pass) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "persist failed");
        return ESP_FAIL;
    }
    ESP_LOGW(TAG, "WiFi creds saved via WebUI (ssid='%s')", ssid);
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, "{\"saved\":true,\"reboot_required\":true}",
                           HTTPD_RESP_USE_STRLEN);
}

static esp_err_t h_wifi_scan(httpd_req_t *req)
{
    static net_scan_entry_t entries[24];
    size_t got = 0;
    if (net_scan(entries, sizeof(entries) / sizeof(entries[0]), &got) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "scan failed");
        return ESP_FAIL;
    }
    static char buf[1800];
    int p = snprintf(buf, sizeof(buf), "[");
    for (size_t i = 0; i < got && p < (int)sizeof(buf) - 128; i++) {
        char esc[66] = {0};
        json_escape(entries[i].ssid, esc, sizeof(esc));
        p += snprintf(buf + p, sizeof(buf) - p,
                      "%s{\"ssid\":\"%s\",\"rssi\":%d,\"ch\":%u,\"auth\":\"%s\"}",
                      i ? "," : "", esc, (int)entries[i].rssi,
                      (unsigned)entries[i].channel, authmode_str(entries[i].authmode));
    }
    p += snprintf(buf + p, sizeof(buf) - p, "]");
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, buf, p);
}

static esp_err_t h_wifi_reset(httpd_req_t *req)
{
    if (net_clear_creds() != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "nvs erase failed");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"reset\":true,\"reboot\":true}", HTTPD_RESP_USE_STRLEN);
    xTaskCreate(delayed_reboot_task, "reboot-cred", 2048, NULL, 5, NULL);
    return ESP_OK;
}

// ───── /api/update/install — HTTPS-pull OTA from the release server ─────

static esp_err_t h_update_install(httpd_req_t *req)
{
    esp_err_t e = ota_install_start();
    httpd_resp_set_type(req, "application/json");
    if (e == ESP_ERR_INVALID_STATE) {
        return httpd_resp_send(req, "{\"installing\":true,\"note\":\"already running\"}",
                               HTTPD_RESP_USE_STRLEN);
    }
    if (e != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "install start failed");
        return ESP_FAIL;
    }
    return httpd_resp_send(req, "{\"installing\":true}", HTTPD_RESP_USE_STRLEN);
}

// ───── init ─────────────────────────────────────────────────────────────

esp_err_t webui_init(uint16_t port)
{
    if (s_http) return ESP_OK;

    httpd_config_t cfg   = HTTPD_DEFAULT_CONFIG();
    cfg.server_port      = port ? port : 80;
    cfg.lru_purge_enable = true;
    cfg.max_uri_handlers = 22;
    cfg.max_open_sockets = 4;
    cfg.recv_wait_timeout = 30;
    cfg.send_wait_timeout = 30;
    cfg.stack_size       = 8192;   // h_ota needs headroom (recv buf + flash + lwIP)

    if (httpd_start(&s_http, &cfg) != ESP_OK) {
        ESP_LOGE(TAG, "httpd_start failed");
        return ESP_FAIL;
    }

    httpd_uri_t u;
    u = (httpd_uri_t){ .uri="/",                 .method=HTTP_GET,  .handler=h_index };        httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/status",       .method=HTTP_GET,  .handler=h_status };       httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/log",          .method=HTTP_GET,  .handler=h_log };          httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/reboot",       .method=HTTP_POST, .handler=h_reboot };       httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/ota",          .method=HTTP_POST, .handler=h_ota };          httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/update/check", .method=HTTP_GET,  .handler=h_update_check }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/update/check", .method=HTTP_POST, .handler=h_update_check }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/update/install",.method=HTTP_POST,.handler=h_update_install }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/config",        .method=HTTP_GET, .handler=h_config_get };  httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/config",        .method=HTTP_POST,.handler=h_config_post }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/serial",        .method=HTTP_GET, .handler=h_serial_get };  httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/serial",        .method=HTTP_POST,.handler=h_serial_post }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/wifi",          .method=HTTP_POST,.handler=h_wifi };        httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/wifi/scan",     .method=HTTP_GET, .handler=h_wifi_scan };   httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/api/wifi/reset",    .method=HTTP_POST,.handler=h_wifi_reset };  httpd_register_uri_handler(s_http, &u);

    // Captive-portal probes (Android/Apple/Windows) → 302 to "/".
    u = (httpd_uri_t){ .uri="/generate_204",       .method=HTTP_GET, .handler=h_captive_redirect }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/gen_204",            .method=HTTP_GET, .handler=h_captive_redirect }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/hotspot-detect.html",.method=HTTP_GET, .handler=h_captive_redirect }; httpd_register_uri_handler(s_http, &u);
    u = (httpd_uri_t){ .uri="/ncsi.txt",           .method=HTTP_GET, .handler=h_captive_redirect }; httpd_register_uri_handler(s_http, &u);
    httpd_register_err_handler(s_http, HTTPD_404_NOT_FOUND, h_not_found);

    ESP_LOGI(TAG, "WebUI on http://%s:%u/", net_ip_str(), cfg.server_port);
    return ESP_OK;
}
